=== janluak/aws-serverless-wrapper/tests/database/noSQL/dynamo_db/test_data/tables/TableForTests.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TableForTests",
  "description": "This is an example schema for creating a dynamo_db table/validating items against",
  "type": "object",
  "additionalProperties": false,
  "default": [
    "primary_partition_key"
  ],
  "properties": {
    "primary_partition_key": {
      "description": "the primary partition key of the dynamo db",
      "type": "string"
    },
    "some_string": {
      "description": "some key containing any kind of strings",
      "type": "string",
      "enum": ["abcdef", "ghijkl", "NewBee"]
    },
    "some_int": {
      "description": "some key containing any integers",
      "type": "integer"
    },
    "some_float": {
      "description": "some key containing any floats",
      "type": "number"
    },
    "some_dict": {
      "description": "containing a simple dictionary",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "key1": {
          "description": "dictionary with key's value type string",
          "type": "string"
        },
        "key2": {
          "description": "dictionary with key's value type number",
          "type": "number"
        }
      }
    },
    "some_nested_dict": {
      "description": "containing a nested_dict",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "KEY1": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "subKEY1": {
              "type": "string"
            },
            "subKEY2": {
              "type": "number"
            },
            "subKEY3": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "some_array": {
      "description": "contains a list",
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "number"
        },
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "KEY1": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "subKEY1": {
                  "type": "string"
                },
                "subKEY2": {
                  "type": "number"
                }
              }
            }
          }
        }
      ]
    }
  },
  "required": [
    "primary_partition_key",
    "some_string",
    "some_int",
    "some_float",
    "some_dict",
    "some_nested_dict",
    "some_array"
  ]
}

=== janluak/aws-serverless-wrapper/tests/database/noSQL/dynamo_db/test_data/items/test_item.json
{
  "primary_partition_key": "some_identification_string",
  "some_string": "abcdef",
  "some_int": 42,
  "some_float": 13.42,
  "some_dict": {
    "key1": "value1",
    "key2": 2
  },
  "some_nested_dict": {
    "KEY1": {
      "subKEY1": "subVALUE1",
      "subKEY2": 42.24
    }
  },
  "some_array": [
    "simple_string",
    13,
    {
      "KEY1": {
        "subKEY1": "subVALUE1",
        "subKEY2": 42.24
      }
    }
  ]
}
